# Generated by Django 3.1.1 on 2020-09-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHuntElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('upvotes', models.IntegerField()),
                ('link', models.URLField(max_length=600, null=True)),
            ],
        ),
    ]
