# Generated by Django 3.1.1 on 2020-09-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=600, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producthuntelement',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
