# Generated by Django 3.1.1 on 2020-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200913_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('searchCount', models.CharField(max_length=500)),
                ('rank', models.URLField(max_length=600, null=True)),
            ],
        ),
    ]
