# Generated by Django 3.1.1 on 2020-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20200913_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditActivityElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subscribers', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditGrowthElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('growth', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditSubscribersElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subscribers', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=600, null=True)),
            ],
        ),
    ]
